### PR TITLE
Fixed co_qualname

### LINKED ISSUE #40: Some new error
this error appeared recently after changing the source code. it didn't exist before and the program worked without problems.

If run as root:

```
INFO - PyMCTranslate Version 208
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'

If run without root:

INFO - PyMCTranslate Version 208
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-Max'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
ERROR - 'code' object has no attribute 'co_qualname'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 381, in scan_plugins
    mod = import_module(plugin_uid.identifier)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load
  File "/usr/local/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 219, in __getitem__
    _validate_import(imported_name, frame)
  File "/usr/local/lib/python3.9/site-packages/amulet_editor/data/plugin/_manager.py", line 154, in _validate_import
    if frame.f_globals.get("__name__") == __name__ and frame.f_code.co_qualname in {
AttributeError: 'code' object has no attribute 'co_qualname'
```

### PR DESCRIPTION
**Pull request by gentlegiantJGC**
co_qualname does not exist on linux. This is a workaround for that.

Fixes #40

### CODE REVIEW

**Comment by Max-RM** [comment]
thx. part of the problem is gone, but there is still this problem: QStandardPaths: 

XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root' 

during the program start. this prevents the program window from starting

**Comment by gentlegiantJGC** [comment]
I can't reproduce that issue on ubuntu. It looks like a warning not an error.
https://unix.stackexchange.com/questions/382789/qstandardpaths-xdg-runtime-dir-not-set-defaulting-to-tmp-runtime-root-when

The application isn't loading on ubuntu which is a different issue that I will need to look into.

**Comment by Max-RM** [comment]
> I can't reproduce that issue on ubuntu. It looks like a warning not an error. https://unix.stackexchange.com/questions/382789/qstandardpaths-xdg-runtime-dir-not-set-defaulting-to-tmp-runtime-root-when
> 
> The application isn't loading on ubuntu which is a different issue that I will need to look into.

I'm use Debian (stable)

**Comment by Max-RM** [comment]
> The application isn't loading on ubuntu which is a different issue that I will need to look into.

previously, the application was launched without problems. now there is only a terminal.

**Pull request merged**
